INSERT INTO customers (first_name, last_name, email) VALUES
('Иван', 'Иванов', 'ivan1@example.com'),
('Петр', 'Петров', 'petr1@example.com'),
('Сергей', 'Сергеев', 'sergey1@example.com'),
('Алексей', 'Алексеев', 'alex1@example.com'),
('Дмитрий', 'Дмитриев', 'dmitry1@example.com'),
('Андрей', 'Андреев', 'andrey1@example.com'),
('Михаил', 'Михайлов', 'mikhail1@example.com'),
('Анна', 'Иванова', 'anna1@example.com'),
('Елена', 'Петрова', 'elena1@example.com'),
('Ольга', 'Сидорова', 'olga1@example.com'),
('Николай', 'Николаев', 'nikolay1@example.com'),
('Артем', 'Артемьев', 'artem1@example.com'),
('Владимир', 'Владимиров', 'vladimir1@example.com'),
('Константин', 'Константинов', 'konstantin1@example.com'),
('Геннадий', 'Геннадиев', 'gennadiy1@example.com'),
('Василий', 'Васильев', 'vasiliy1@example.com'),
('Виктор', 'Викторов', 'viktor1@example.com'),
('Юрий', 'Юрьев', 'yuriy1@example.com'),
('Максим', 'Максимов', 'maksim1@example.com'),
('Роман', 'Романов', 'roman1@example.com'),
('Иван', 'Смирнов', 'ivan2@example.com'),
('Петр', 'Кузнецов', 'petr2@example.com'),
('Сергей', 'Попов', 'sergey2@example.com'),
('Алексей', 'Васильев', 'alex2@example.com'),
('Дмитрий', 'Павлов', 'dmitry2@example.com'),
('Андрей', 'Семенов', 'andrey2@example.com'),
('Михаил', 'Голубев', 'mikhail2@example.com'),
('Анна', 'Козлова', 'anna2@example.com'),
('Елена', 'Новикова', 'elena2@example.com'),
('Ольга', 'Морозова', 'olga2@example.com'),
('Татьяна', 'Волкова', 'tatyana1@example.com'),
('Наталья', 'Соловьева', 'natalya1@example.com'),
('Мария', 'Лебедева', 'maria1@example.com'),
('Светлана', 'Егорова', 'svetlana1@example.com'),
('Екатерина', 'Козлова', 'ekaterina1@example.com'),
('Ирина', 'Николаева', 'irina1@example.com'),
('Оксана', 'Захарова', 'oksana1@example.com'),
('Людмила', 'Степанова', 'lyudmila1@example.com'),
('Галина', 'Орлова', 'galina1@example.com'),
('Валентина', 'Антипова', 'valentina1@example.com'),
('Иван', 'Макаров', 'ivan3@example.com'),
('Петр', 'Андреев', 'petr3@example.com'),
('Сергей', 'Никитин', 'sergey3@example.com'),
('Алексей', 'Соболев', 'alex3@example.com'),
('Дмитрий', 'Дорофеев', 'dmitry3@example.com'),
('Андрей', 'Елисеев', 'andrey3@example.com'),
('Михаил', 'Борисов', 'mikhail3@example.com'),
('Анна', 'Полякова', 'anna3@example.com'),
('Елена', 'Данилова', 'elena3@example.com'),
('Ольга', 'Жукова', 'olga3@example.com'),
('Иван', 'Федоров', 'ivan4@example.com'),
('Петр', 'Медведев', 'petr4@example.com'),
('Сергей', 'Ершов', 'sergey4@example.com'),
('Алексей', 'Щукин', 'alex4@example.com'),
('Дмитрий', 'Савельев', 'dmitry4@example.com'),
('Андрей', 'Рыбаков', 'andrey4@example.com'),
('Михаил', 'Суханов', 'mikhail4@example.com'),
('Анна', 'Тихонова', 'anna4@example.com'),
('Елена', 'Фомина', 'elena4@example.com'),
('Ольга', 'Давыдова', 'olga4@example.com'),
('Татьяна', 'Журавлева', 'tatyana2@example.com'),
('Наталья', 'Прохорова', 'natalya2@example.com'),
('Мария', 'Назарова', 'maria2@example.com'),
('Светлана', 'Потапова', 'svetlana2@example.com'),
('Екатерина', 'Гусева', 'ekaterina2@example.com'),
('Ирина', 'Титова', 'irina2@example.com'),
('Оксана', 'Кузьмина', 'oksana2@example.com'),
('Людмила', 'Кудрявцева', 'lyudmila2@example.com'),
('Галина', 'Баранова', 'galina2@example.com'),
('Валентина', 'Герасимова', 'valentina2@example.com'),
('Иван', 'Богданов', 'ivan5@example.com'),
('Петр', 'Осипов', 'petr5@example.com'),
('Сергей', 'Силин', 'sergey5@example.com'),
('Алексей', 'Лаптев', 'alex5@example.com'),
('Дмитрий', 'Беляев', 'dmitry5@example.com'),
('Андрей', 'Мухин', 'andrey5@example.com'),
('Михаил', 'Широков', 'mikhail5@example.com'),
('Анна', 'Филиппова', 'anna5@example.com'),
('Елена', 'Маркова', 'elena5@example.com'),
('Ольга', 'Большакова', 'olga5@example.com'),
('Татьяна', 'Суворова', 'tatyana3@example.com'),
('Наталья', 'Крылова', 'natalya3@example.com'),
('Мария', 'Кондратьева', 'maria3@example.com'),
('Светлана', 'Исаева', 'svetlana3@example.com'),
('Екатерина', 'Горбунова', 'ekaterina3@example.com'),
('Ирина', 'Лыткина', 'irina3@example.com'),
('Оксана', 'Соколова', 'oksana3@example.com'),
('Людмила', 'Виноградова', 'lyudmila3@example.com'),
('Галина', 'Зайцева', 'galina3@example.com'),
('Валентина', 'Карпова', 'valentina3@example.com'),
('Иван', 'Афанасьев', 'ivan6@example.com'),
('Петр', 'Воробьев', 'petr6@example.com'),
('Сергей', 'Парамонов', 'sergey6@example.com'),
('Алексей', 'Галкин', 'alex6@example.com'),
('Дмитрий', 'Наумов', 'dmitry6@example.com'),
('Андрей', 'Савин', 'andrey6@example.com'),
('Михаил', 'Белов', 'mikhail6@example.com'),
('Анна', 'Калашникова', 'anna6@example.com'),
('Елена', 'Киселева', 'elena6@example.com'),
('Ольга', 'Дементьева', 'olga6@example.com'),
('Татьяна', 'Гаврилова', 'tatyana4@example.com'),
('Наталья', 'Третьякова', 'natalya4@example.com'),
('Мария', 'Куликова', 'maria4@example.com'),
('Светлана', 'Игнатова', 'svetlana4@example.com'),
('Екатерина', 'Логинова', 'ekaterina4@example.com'),
('Ирина', 'Сафонова', 'irina4@example.com'),
('Оксана', 'Капустина', 'oksana4@example.com'),
('Людмила', 'Кириллова', 'lyudmila4@example.com'),
('Галина', 'Евсеева', 'galina4@example.com'),
('Валентина', 'Гордеева', 'valentina4@example.com'),
('Иван', 'Князев', 'ivan7@example.com'),
('Петр', 'Потапов', 'petr7@example.com'),
('Сергей', 'Жданов', 'sergey7@example.com'),
('Алексей', 'Орехов', 'alex7@example.com'),
('Дмитрий', 'Денисов', 'dmitry7@example.com'),
('Андрей', 'Громов', 'andrey7@example.com'),
('Михаил', 'Терентьев', 'mikhail7@example.com'),
('Анна', 'Молчанова', 'anna7@example.com'),
('Елена', 'Власова', 'elena7@example.com'),
('Ольга', 'Артемьева', 'olga7@example.com'),
('Татьяна', 'Королева', 'tatyana5@example.com'),
('Наталья', 'Руднева', 'natalya5@example.com'),
('Мария', 'Лазарева', 'maria5@example.com'),
('Светлана', 'Белоусова', 'svetlana5@example.com'),
('Екатерина', 'Нестерова', 'ekaterina5@example.com'),
('Ирина', 'Симонова', 'irina5@example.com'),
('Оксана', 'Фадеева', 'oksana5@example.com'),
('Людмила', 'Комарова', 'lyudmila5@example.com'),
('Галина', 'Данилова', 'galina5@example.com'),
('Валентина', 'Островская', 'valentina5@example.com'),
('Иван', 'Титов', 'ivan8@example.com'),
('Петр', 'Сазонов', 'petr8@example.com'),
('Сергей', 'Зимин', 'sergey8@example.com'),
('Алексей', 'Костин', 'alex8@example.com'),
('Дмитрий', 'Шестаков', 'dmitry8@example.com'),
('Андрей', 'Яковлев', 'andrey8@example.com'),
('Михаил', 'Григорьев', 'mikhail8@example.com'),
('Анна', 'Романова', 'anna8@example.com'),
('Елена', 'Воронова', 'elena8@example.com'),
('Ольга', 'Серова', 'olga8@example.com'),
('Татьяна', 'Павлова', 'tatyana6@example.com'),
('Наталья', 'Бирюкова', 'natalya6@example.com'),
('Мария', 'Седова', 'maria6@example.com'),
('Светлана', 'Галкина', 'svetlana6@example.com'),
('Екатерина', 'Коновалова', 'ekaterina6@example.com'),
('Ирина', 'Ларина', 'irina6@example.com'),
('Оксана', 'Ефимова', 'oksana6@example.com'),
('Людмила', 'Тарасова', 'lyudmila6@example.com'),
('Галина', 'Белова', 'galina6@example.com'),
('Валентина', 'Чернова', 'valentina6@example.com'),
('Иван', 'Маслов', 'ivan9@example.com'),
('Петр', 'Родионов', 'petr9@example.com'),
('Сергей', 'Сотников', 'sergey9@example.com'),
('Алексей', 'Блинов', 'alex9@example.com'),
('Дмитрий', 'Колесников', 'dmitry9@example.com'),
('Андрей', 'Карпов', 'andrey9@example.com'),
('Михаил', 'Афанасьев', 'mikhail9@example.com'),
('Анна', 'Власова', 'anna9@example.com'),
('Елена', 'Мельникова', 'elena9@example.com'),
('Ольга', 'Коваленко', 'olga9@example.com'),
('Татьяна', 'Ильина', 'tatyana7@example.com'),
('Наталья', 'Горелова', 'natalya7@example.com'),
('Мария', 'Никифорова', 'maria7@example.com'),
('Светлана', 'Еремина', 'svetlana7@example.com'),
('Екатерина', 'Голубева', 'ekaterina7@example.com'),
('Ирина', 'Котова', 'irina7@example.com'),
('Оксана', 'Гришина', 'oksana7@example.com'),
('Людмила', 'Ефремова', 'lyudmila7@example.com'),
('Галина', 'Терентьева', 'galina7@example.com'),
('Валентина', 'Мартынова', 'valentina7@example.com'),
('Иван', 'Чернов', 'ivan10@example.com'),
('Петр', 'Беляков', 'petr10@example.com'),
('Сергей', 'Беспалов', 'sergey10@example.com'),
('Алексей', 'Доронин', 'alex10@example.com'),
('Дмитрий', 'Савицкий', 'dmitry10@example.com'),
('Андрей', 'Галкин', 'andrey10@example.com'),
('Михаил', 'Козловский', 'mikhail10@example.com'),
('Анна', 'Шарова', 'anna10@example.com'),
('Елена', 'Селезнева', 'elena10@example.com'),
('Ольга', 'Панфилова', 'olga10@example.com');


INSERT INTO orders (customer, total) VALUES
(7, 1200),
(8, 300),
(9, 2450),
(7, 1800),
(10, 420),
(8, 3150),
(11, 950),
(9, 2700),
(7, 380),
(12, 1950),
(10, 560),
(8, 3250),
(13, 720),
(11, 410),
(9, 2870),
(7, 630),
(14, 1520),
(12, 840),
(10, 3620),
(8, 510),
(15, 2280),
(13, 670),
(11, 1430),
(9, 790),
(7, 2750),
(16, 350),
(14, 1980),
(12, 580),
(10, 3320),
(8, 420),
(17, 2640),
(15, 710),
(13, 1870),
(11, 930),
(9, 2980),
(7, 480),
(18, 2130),
(16, 650),
(14, 1540),
(12, 820),
(10, 3410),
(8, 390),
(19, 2260),
(17, 540),
(15, 1760),
(13, 680),
(11, 2890),
(9, 470),
(7, 2030),
(20, 590),
(18, 3170),
(16, 440),
(14, 2380),
(12, 760),
(10, 1650),
(8, 850),
(21, 3540),
(19, 370),
(17, 2190),
(15, 520),
(13, 1420),
(11, 780),
(9, 3010),
(7, 460),
(22, 1920),
(20, 610),
(18, 3280),
(16, 400),
(14, 2470),
(12, 730),
(10, 1580),
(8, 910),
(23, 2830),
(21, 490),
(19, 2070),
(17, 550),
(15, 3360),
(13, 430),
(11, 2290),
(9, 690),
(7, 1710),
(24, 880),
(22, 2940),
(20, 360),
(18, 2110),
(16, 640),
(14, 3470),
(12, 450),
(10, 2330),
(8, 770),
(25, 1630),
(23, 890),
(21, 3120),
(19, 530),
(17, 1840),
(15, 620),
(13, 2790),
(11, 470),
(9, 2240);